version: '3'

services:
  core:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    networks:
      - my_bridge

networks:
  my_bridge:
